### PR TITLE
Adds override examples to the docs

### PR DESCRIPTION
**Pull request by mslw**
Based on
https://github.com/psychoinformatics-de/datalad-tabby/pull/47#issuecomment-1628922125
(both simplified and extended here), I believe these examples may help
understand how overrides work and what they look like.

Naturally, if my examples are missing the point or are suboptimal,
feel free to change or reject them -- I feel I didn't hit the exact
intended purpose.

### CODE REVIEW

**Comment by mih** [comment]
I think this is all spot-on. Thx!

**Review by jsheunis — CHANGES_REQUESTED** [review]
I found the examples helpful, thanks!

Also agree with @mih's comments about keeping examples separate and cross-linking where appropriate.

**Comment by mslw** [comment]
Thank you for the feedback - I agree that it looks better when examples are separate. I moved the examples to a new page.

**Review by mih — APPROVED** [review]
Thx!

**Pull request merged**
